### ISSUE TITLE
GLIBC_2.32 and GLIBC_2.34 not found for consul-lambda-registrator

### ISSUE THREAD

**Issue by horvvpeter** [hashicorp/terraform-aws-consul-lambda#57]
Hello,

I've tried to set up the automatic Lambda registration based on [this](https://developer.hashicorp.com/consul/docs/lambda/registration/automate) documentation but got into an issue.

### Steps I made

1. Pulled the https://gallery.ecr.aws/hashicorp/consul-lambda-registrator Docker image with tag 0.1.0-beta3 and pushed it to a private ECR repository
2. Deployed the https://github.com/hashicorp/terraform-aws-consul-lambda/tree/main/modules/lambda-registrator Terraform module. Here I set the `ecr_image_uri` to point to my private version of the consul-lambda-registrator Docker image
3. Waited for an event to trigger the Lambda/ manually triggered it
4. Got this error when running the Lambda:

> /bin/consul-lambda-registrator: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by /bin/consul-lambda-registrator)
/bin/consul-lambda-registrator: /lib64/libc.so.6: version 'GLIBC_2.34' not found (required by /bin/consul-lambda-registrator)
START RequestId: f41cd4cb-ff3b-401f-aede-b83e4089f268 Version: $LATEST
RequestId: f41cd4cb-ff3b-401f-aede-b83e4089f268 Error: Runtime exited with error: exit status 1
Runtime.ExitError
END RequestId: f41cd4cb-ff3b-401f-aede-b83e4089f268
REPORT RequestId: f41cd4cb-ff3b-401f-aede-b83e4089f268	Duration: 23.32 ms	Billed Duration: 24 ms	Memory Size: 128 MB	Max Memory Used: 3 MB

Do you have any advice for this? After doing some research it seems to me that the consul-lambda-registrator might need to be build with `CGO_ENABLED=0`

Thanks!

**Comment by cthain** [comment]
:wave: Hi @horvvpeter, thanks for raising this issue. I have confirmed the behavior you reported, both in the AWS Lambda runtime and locally:

```sh
github.com/hashicorp/terraform-aws-consul-lambda/consul-lambda$ docker run --rm \
    public.ecr.aws/hashicorp/consul-lambda-registrator:0.1.0-beta3
/bin/consul-lambda-registrator: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /bin/consul-lambda-registrator)
/bin/consul-lambda-registrator: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /bin/consul-lambda-registrator)
```
I also confirmed that adding `CGO_ENABLED=0` to the build fixes the issue:

```sh
github.com/hashicorp/terraform-aws-consul-lambda/consul-lambda$ make docker
cd consul-lambda-registrator && GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -ldflags "-X "github.com/hashicorp/terraform-aws-consul-lambda/consul-lambda/version.GitCommit=9b454c2+CHANGES"" -o dist/linux/amd64/consul-lambda-registrator

github.com/hashicorp/terraform-aws-consul-lambda/consul-lambda$ docker run --rm \
    consul-lambda-registrator/release-default:0.1.0-beta3
2023/03/31 14:50:30 expected AWS Lambda environment variables [_LAMBDA_SERVER_PORT AWS_LAMBDA_RUNTIME_API] are not defined
```

As for the cause of this issue, I believe it has something to do with the [`cgo` changes introduced in Go 1.20](https://go.dev/doc/go1.20#cgo). I haven't fully traced the cause but this seems like a reasonable culprit considering we recently upgraded to Go 1.20. I've confirmed that everything "just works" if I use the Go 1.19 toolchain. That is, without needing to add the `CGO_ENABLED=0` flag.

I'm not sure how our acceptance tests missed this :thinking:. I'll have to look into it.

I think this is going to require an updated release to fix this issue.

As a workaround, you could build the `consul-lambda-registrator` docker image locally and push it to your private ECR instead of using our official image:

```sh
$ go version
go version go1.20.2 linux/amd64
$ cd terraform-aws-consul-lambda/consul-lambda
$ sed -i 's/go build/CGO_ENABLED=0 go build/' Makefile
$ make docker
$ docker tag \
  consul-lambda-registrator/release-default:0.1.0-beta3 \
  ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/consul-lambda-registrator:0.1.0-beta3
$ docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/consul-lambda-registrator:0.1.0-beta3
```

Thanks again for raising the issue and sorry for any inconvenience.

**Comment by horvvpeter** [comment]
Hi @cthain,

Thanks for the quick reply and confirmation! I will check the local build.
